### ISSUE TITLE
Change output of pre and post rollout task logs

### ISSUE THREAD

**Issue by shreddedbacon** [uselagoon/build-deploy-tool#155]
If a user tries to run a pre or post rollout task in an `nginx-php-persistent` or any other `x-persistent` service, it will fail because there are 2 or more containers in the pod (with rootless workloads, there is the init container, with php there are three containers)

The [docs ask a user to provide the `service`](https://docs.lagoon.sh/using-lagoon-the-basics/lagoon-yml/#post-rollout-tasks-post_rolloutirun) to run the task in, but in no place do we mention the container to also use.

[We call out this problem with SSH](https://docs.lagoon.sh/using-lagoon-advanced/ssh/#podservice-container-definition), so we should support this option for tasks too

Example: requires the user to specify `nginx`, `php`, or `fix-storage-permissions` (the last one being the init container for rootless)
```
Executing Post-rollout Tasks
Executing task 'Deletes all cached pages':'rm -rf storage/cache/blitz'
Going to exec into  nginx-5fd488b7dc-gbj52
*** Task 'Deletes all cached pages' failed - STDOUT and STDERR follows ***
Post-rollout Tasks Failed with the following error:  Error returned: a container name must be specified for pod nginx-5fd488b7dc-gbj52, choose one of: [fix-storage-permissions nginx php]
```

**Comment by tobybellwood** [comment]
The task run should accept a container as an option? https://github.com/uselagoon/build-deploy-tool/blob/main/cmd/tasks_run.go#L256 and https://github.com/uselagoon/build-deploy-tool/blob/main/internal/lagoon/tasks.go#L127

**Comment by shreddedbacon** [comment]
I guess this is just a documentation update then

**Comment by tobybellwood** [comment]
can confirm that specifying the container in the task does work

```
tasks:
  post-rollout:
    - run:
        name: env variables
        command: env
        service: nginx
        container: php
```
gets you
```
Executing Post-rollout Tasks
Executing task 'env variables':'env'
Going to exec into  nginx-796956686c-nf89g
*** Task STDOUT ***
HOSTNAME=nginx-796956686c-nf89g
PHP_INI_DIR=/usr/local/etc/php
PHP_VERSION=8.1.13
LAGOON=php
```

**Comment by shreddedbacon** [comment]
I think the messaging in the logs needs some tweaking anyway, so yep

**Comment by bomoko** [comment]
@tobybellwood - I'll add that quick.

@shreddedbacon - cool, I'm happy to change the messaging - but if you have specific changes in mind, will you make the changes? Or can you write 'em here and I'll bundle them here with the container message Toby suggested.

**Comment by shreddedbacon** [comment]
> @shreddedbacon - cool, I'm super happy to change the messaging - but if you have specific changes in mind, will you be making the changes? Or can you write 'em here and I'll bundle them here with the container message Toby suggested (probably easier/better?).

This is overall messaging in the build-deploy-tool, so just fix the container message for now, will raise a separate issue to discuss the other messaging

**Comment by bomoko** [comment]
gotcha, will do
