### ISSUE TITLE
Lagoon doesn't support dots in service names

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/build-deploy-tool#157]
Docker Compose supports `[a-zA-Z0-9\._\-]` in service names (https://github.com/docker/compose/pull/1624) as per the compose spec `"^[a-zA-Z0-9._-]+$"` (https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json#LL23C9-L23C28)

Lagoon however, can't handle periods in service names in at least two places:
1) Our shyaml `hyaml get-value services.$COMPOSE_SERVICE.labels.lagoon\\.name` tries to interpret the `.` as dot notation (need to escape the . with a `)
2) Any ingresses would end up with a different  subdomain (replace . with -)

**Comment by tobybellwood** [comment]
Kubernetes does not support dots in service names either. @CGoodwin90 has looked at this, and whilst the shyaml and autogen ingresses are an easy solve, the service name has deeper ramifications

We would have to auto replace the service names `.` with `-`, but then any functionality or internal names used in the application would break in production (i.e being able to reference another pod by it's name would have to be done using the - in kubernetes, and the . in docker-compose, by which point it's better to replace it everywhere)

IMO, not worth pursuing.

**Comment by shreddedbacon** [comment]
Should we fail a build if someone defines a service with a `.` in the name?

**Comment by tobybellwood** [comment]
I think that would be prudent - the error messages out of the build tool are not helpful currently in understanding exactly what's gone wrong.

**Comment by tobybellwood** [comment]
by the docs (https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service)

> The name of a Service object must be a valid [RFC 1035 label name](https://kubernetes.io/docs/concepts/overview/working-with-objects/names#rfc-1035-label-names).

- contain at most 63 characters
- contain only lowercase alphanumeric characters or '-'
- start with an alphabetic character
- end with an alphanumeric character

**Comment by shreddedbacon** [comment]
Yep
