### ISSUE TITLE
docker-compose validation failure with stock SSH_AUTH_SOCK volume

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/build-deploy-tool#166]
When using the SSH_AUTH_SOCK method to pass ssh auth into a docker container (such as https://github.com/lagoon-examples/drupal9-base/blob/buildkit/docker-compose.yml#L9), the build fails the docker-compose validation step, because the environment variable doesn't exist at the point of assessing the file for validity.

We should consider ways to mitigate this error, as this is a valid strategy, either via exception, or documentation?

`1 error(s) decoding: * error decoding 'Volumes[2]': invalid spec: :/ssh-agent: empty section between colons`

**Comment by tobybellwood** [comment]
ugh - it really makes most sense to have a fallback value set for the var (which the validator does respect)
setting `${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent` in the volumes block passes it nicely.

IMO not worth handling as an edge case, unless we have any other potentially undefined variables we're treating?

**Comment by shreddedbacon** [comment]
If this can be handled by a user modifying their docker-compose file or something because its an edge case, I much prefer making a note of it in the docs, than trying to handle this edge case in the tool.
