### ISSUE TITLE
multiline cronjobs cause invalid YAML

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/build-deploy-tool#173]
`build-deploy-tool v0.21.0 (built: 2023-01-19T02:17:50+0000 / go 1.17)`

having a multiline string for the cronjob command has been reported as failing to create valid YAML in the templating stage

```
- name: Some nightly task
        schedule: '5 2 * * *'
        command: |
          /app/scripts/custom_task.sh
```

fails with `Error: YAML parse error on cli-persistent/templates/cronjob.yaml: error converting YAML to JSON: yaml: line 83: did not find expected alphabetic or numeric character`

removal of the | and conversion to single line parses and creates OK

**Comment by shreddedbacon** [comment]
Duplicate? https://github.com/uselagoon/build-deploy-tool/issues/103

**Comment by tobybellwood** [comment]
ha - closing as duplicate
