### ISSUE TITLE
Default HSTS max-age is too short

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/build-deploy-tool#188]
The [default HSTS `max-age`](https://github.com/uselagoon/build-deploy-tool/blob/df8b6d57492f29ba89514afb46df27978303714c/internal/lagoon/routes.go#L62) is `3153600` or ~2 months.

I think this is too short and should be changed to `31536000` (~1 year) because:

1. The minimum max-age for [preloading](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security#preloading_strict_transport_security) is `31536000`
2. The [old `hsts` flag we used](https://github.com/uselagoon/build-deploy-tool/blob/df8b6d57492f29ba89514afb46df27978303714c/test-resources/identify-ingress/test16/lagoon.yml#L20) always had `31536000` as the default example

**Comment by seanhamlin** [comment]
This honestly looks like a typo in the code, +1 to fix that.

**Comment by shreddedbacon** [comment]
Yeah definitely a typo
