### ISSUE TITLE
document fastly environment variables

### ISSUE THREAD

**Issue by domcyrus** [uselagoon/build-deploy-tool#273]
There exist several fastly environment variables throughout this code which are not documented anywhere:
- LAGOON_FASTLY_SERVICE_ID
- LAGOON_FASTLY_NOCACHE_SERVICE_ID
- FASTLY_API_SECRET_PREFIX

**Comment by shreddedbacon** [comment]
closing to reduce spread, main issue in lagoon can track all occurrences https://github.com/uselagoon/lagoon/issues/3609
