### ISSUE TITLE
max-allowed-packet too small in prebackuppod dump command

### ISSUE THREAD

**Issue by smlx** [uselagoon/build-deploy-tool#323]
I found a backup failure caused by the hard-coded `--max-allowed-packet=500M` in the prebackuppod template being too small. The command was failing with this error:

```
mysqldump: Error 2013: Lost connection to server during query when dumping table `cache_config` at row: 23
```

Bumping the value to `600M` allowed the dump to complete.

The protocol maximum of this value is `1G` in both [RDS](https://aws.amazon.com/blogs/database/best-practices-for-configuring-parameters-for-amazon-rds-for-mysql-part-3-parameters-related-to-security-operational-manageability-and-connectivity-timeout/) and [MySQL](https://dev.mysql.com/doc/refman/8.4/en/server-system-variables.html#sysvar_max_allowed_packet). Using that value also worked, so I guess we should just use the maximum value.

![screenshot_2024-06-06-085427](https://github.com/uselagoon/build-deploy-tool/assets/861778/b6333a0f-8c59-4187-a5d9-ea7f88f1aa9e)

The `500M` value is hard-coded in several places. I guess all should be changed?

* https://github.com/uselagoon/build-deploy-tool/blob/997483b59ac7c055a07f04f579b91ccd7e4fb4a2/internal/templating/backups/template_prebackuppod.go#L283
* https://github.com/uselagoon/build-deploy-tool/blob/997483b59ac7c055a07f04f579b91ccd7e4fb4a2/internal/templating/backups/template_prebackuppod.go#L291
* https://github.com/uselagoon/build-deploy-tool/blob/997483b59ac7c055a07f04f579b91ccd7e4fb4a2/legacy/helmcharts/mariadb-single/templates/deployment.yaml#L28

**Comment by shreddedbacon** [comment]
Makes sense to use the max allowed then
