### ISSUE TITLE
Build arg `LAGOON_SSH_PRIVATE_KEY` not available

### ISSUE THREAD

**Issue by rocketeerbkw** [uselagoon/build-deploy-tool#347]
It looks like the change to go has dropped the build arg `LAGOON_SSH_PRIVATE_KEY`. It should be set to the project private key, and it's used to facilitate package managers being able to pull from private repos https://docs.lagoon.sh/using-lagoon-advanced/private-repositories/.

**Comment by shreddedbacon** [comment]
Nice pickup, will get a fix out asap
