### ISSUE TITLE
Run pre-rollout tasks later in the build - ie immediately before the rollout

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/build-deploy-tool#375]
As discussed with @sjerdo - we should look at moving the pre-rollout tasks closer to the rollout - so that any delays pushing images etc to harbor won't hold up a pre-rollout task - allowing for shorter deployment times (for maintenance mode etc)

**Comment by shreddedbacon** [comment]
I think this should be doable. I don't think there is anything that happens between the pre-rollout and the actual rollout (apply deployments) phase that would be reliant on pre-rollouts having completed.
