### ISSUE TITLE
support additional IngressClass in ingresses

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/build-deploy-tool#41]
As an advanced user of Lagoon, managing a dedicated remote cluster, I may wish to install an additional Ingress. the build-deploy-tool should allow me to specify which IngressClass a non-default ingress be mapped to.

**Comment by shreddedbacon** [comment]
How do you think this would work in terms of a user being able to set this?

**Comment by tobybellwood** [comment]
I would imagine either along the lines of the existing ingress annotations - i.e. defined per-route in the .lagoon.yml, or being able to override via the API/variables/build-deploy somehow
