### ISSUE TITLE
Add support for configuring hsts via lagoon.yml on k8s

### ISSUE THREAD

**Issue by thom8** [uselagoon/build-deploy-tool#82]
# Describe the bug

Lagoon's `oc-build-deploy` had support for configuring HSTS headers per route in lagoon.yml, this is currently not available when deploying via `kubectl-build-deploy`

## To Reproduce

1. Add hsts configuration to a route definition
2. Deploy environment with route attached
3. No hsts headers are returned for that route

## Expected behavior

HSTS headers are configured based on the configuration applied in lagoon.yml as describe by our documentation -- https://docs.lagoon.sh/lagoon/using-lagoon-the-basics/lagoon-yml#ssl-configuration-tls-acme

## Possible solutions

Set custom headers via `configuration-snippet` in nginx ingress controller.

```
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "MyCustomHeader: Value";
```

**Comment by shreddedbacon** [comment]
hsts off by default

**Comment by shreddedbacon** [comment]
This would require us to do something like this then?
```
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Securit: max-age=31536000;includeSubDomains;preload";
```

**Comment by seanhamlin** [comment]
Looking at the Lagoon docs:

```
     - "www.example.com":
            tls-acme: 'true'
            hsts: max-age=31536000
```

So the value of the `Strict-Transport-Security` header is what the user writes there.

The only thing I would add is that this header should only be added over HTTPS (not on HTTP).
