### ISSUE TITLE
pre-deploy task doesn't wait long enough for pods to scale up

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/build-deploy-tool#92]
pre-deploy task seem to wait only for 30 secs to scale up the pods, unfortunately in some situations (big images, slightly loaded cluster, etc.) it can take longer than 30secs and the build is failing, here an example
<img width="1657" alt="Screen Shot 2022-08-19 at 16 56 34" src="https://user-images.githubusercontent.com/750999/185706590-1081dab2-c8d1-48ce-b05f-f6356b9f02bb.png">

Is there a simple way to extend the waiting time? I would suggest something around 5 mins.

**Comment by Schnitzel** [comment]
found https://github.com/uselagoon/build-deploy-tool/pull/84 which allows to change the settings and also changes is to 300secs (5mins)

can be closed

**Comment by tobybellwood** [comment]
#84 should resolve this, will be released early next week IIRC
